version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: neighborfit-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: neighborfit
    volumes:
      - mongodb_data:/data/db
      - ./server/data:/docker-entrypoint-initdb.d:ro
    networks:
      - neighborfit-network

volumes:
  mongodb_data:

networks:
  neighborfit-network:
    driver: bridge